//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja_app
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LojaDBEntities : DbContext
    {
        public LojaDBEntities()
            : base("name=LojaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Despesas_Table> Despesas_Table { get; set; }
        public virtual DbSet<IVA_Table> IVA_Table { get; set; }
        public virtual DbSet<Produto_Table> Produto_Table { get; set; }
        public virtual DbSet<Receita_Table> Receita_Table { get; set; }
    }
}
