//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto_Table
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public Nullable<int> IVA { get; set; }
        public Nullable<double> Valor_compra { get; set; }
        public Nullable<double> Valor_final { get; set; }
    
        public virtual IVA_Table IVA_Table { get; set; }
    }
}
