//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Loja_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Receita_Table
    {
        public int ID { get; set; }
        public Nullable<double> Valor { get; set; }
        public Nullable<System.DateTime> Data { get; set; }
    }
}
